export const dummyProfessionals = [
  {
    id: '1',
    name: 'Amadou Diallo',
    title: 'Full Stack Developer',
    location: 'Dakar, Senegal',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 4.9,
    reviewCount: 47,
    projectsCompleted: 52,
    hourlyRate: 35,
    skills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Next.js', 'PostgreSQL'],
    bio: 'Experienced full-stack developer specializing in modern web applications. I help businesses build scalable and performant solutions.',
    bioFr: 'Développeur full-stack expérimenté spécialisé dans les applications web modernes. J\'aide les entreprises à créer des solutions évolutives et performantes.',
    languages: ['English', 'French', 'Wolof'],
    portfolio: [
      {
        id: '1',
        title: 'E-commerce Platform',
        titleFr: 'Plateforme E-commerce',
        image: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=500',
        description: 'Built a complete e-commerce solution for a local retailer',
      },
      {
        id: '2',
        title: 'Mobile Banking App',
        titleFr: 'Application Bancaire Mobile',
        image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=500',
        description: 'Developed secure mobile banking application',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Marie Ndiaye',
        rating: 5,
        comment: 'Excellent work! Very professional and delivered on time.',
        commentFr: 'Excellent travail! Très professionnel et livré à temps.',
        date: '2026-04-15',
      },
    ],
  },
  {
    id: '2',
    name: 'Fatou Sanneh',
    title: 'UI/UX Designer',
    location: 'Banjul, Gambia',
    avatar: 'https://i.pravatar.cc/150?img=45',
    rating: 5.0,
    reviewCount: 38,
    projectsCompleted: 41,
    hourlyRate: 30,
    skills: ['Figma', 'Adobe XD', 'Illustrator', 'User Research', 'Prototyping', 'Branding'],
    bio: 'Creative UI/UX designer with a passion for creating beautiful and intuitive user experiences. I focus on user-centered design.',
    bioFr: 'Designer UI/UX créative avec une passion pour créer des expériences utilisateur belles et intuitives. Je me concentre sur le design centré sur l\'utilisateur.',
    languages: ['English', 'French'],
    portfolio: [
      {
        id: '1',
        title: 'Travel App Design',
        titleFr: 'Design d\'Application de Voyage',
        image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500',
        description: 'Complete UI/UX design for a travel booking platform',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Lamin Jallow',
        rating: 5,
        comment: 'Amazing designer! She understood exactly what we needed.',
        commentFr: 'Designer incroyable! Elle a compris exactement ce dont nous avions besoin.',
        date: '2026-04-20',
      },
    ],
  },
  {
    id: '3',
    name: 'Ibrahima Sarr',
    title: 'Digital Marketing Specialist',
    location: 'Dakar, Senegal',
    avatar: 'https://i.pravatar.cc/150?img=33',
    rating: 4.8,
    reviewCount: 31,
    projectsCompleted: 35,
    hourlyRate: 28,
    skills: ['SEO', 'Social Media Marketing', 'Content Strategy', 'Google Ads', 'Analytics', 'Email Marketing'],
    bio: 'Digital marketing expert helping businesses grow their online presence. Specialized in African markets with proven results.',
    bioFr: 'Expert en marketing digital aidant les entreprises à développer leur présence en ligne. Spécialisé dans les marchés africains avec des résultats prouvés.',
    languages: ['French', 'English', 'Wolof'],
    portfolio: [
      {
        id: '1',
        title: 'Social Media Campaign',
        titleFr: 'Campagne de Médias Sociaux',
        image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500',
        description: 'Successful social media campaign reaching 100K+ people',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Awa Diop',
        rating: 5,
        comment: 'Our sales increased by 150% after his campaign!',
        commentFr: 'Nos ventes ont augmenté de 150% après sa campagne!',
        date: '2026-03-10',
      },
    ],
  },
  {
    id: '4',
    name: 'Mariama Jaiteh',
    title: 'Content Writer & Translator',
    location: 'Banjul, Gambia',
    avatar: 'https://i.pravatar.cc/150?img=47',
    rating: 4.9,
    reviewCount: 56,
    projectsCompleted: 68,
    hourlyRate: 25,
    skills: ['Content Writing', 'Translation', 'Copywriting', 'SEO Writing', 'Blogging', 'Proofreading'],
    bio: 'Bilingual content writer and translator. I create engaging content in English and French that resonates with African audiences.',
    bioFr: 'Rédactrice et traductrice bilingue. Je crée du contenu engageant en anglais et en français qui résonne avec les audiences africaines.',
    languages: ['English', 'French', 'Mandinka'],
    portfolio: [
      {
        id: '1',
        title: 'Blog Content Series',
        titleFr: 'Série de Contenu de Blog',
        image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=500',
        description: 'Created 50+ blog posts for tech startup',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Omar Ba',
        rating: 5,
        comment: 'Her writing is engaging and always delivered on schedule.',
        commentFr: 'Son écriture est engageante et toujours livrée à temps.',
        date: '2026-04-01',
      },
    ],
  },
  {
    id: '5',
    name: 'Moussa Kamara',
    title: 'Mobile App Developer',
    location: 'Dakar, Senegal',
    avatar: 'https://i.pravatar.cc/150?img=15',
    rating: 4.7,
    reviewCount: 29,
    projectsCompleted: 33,
    hourlyRate: 40,
    skills: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase', 'API Integration'],
    bio: 'Mobile app developer creating cross-platform applications. I build apps that work seamlessly on both iOS and Android.',
    bioFr: 'Développeur d\'applications mobiles créant des applications multiplateformes. Je construis des applications qui fonctionnent parfaitement sur iOS et Android.',
    languages: ['French', 'English'],
    portfolio: [
      {
        id: '1',
        title: 'Delivery App',
        titleFr: 'Application de Livraison',
        image: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=500',
        description: 'Built a food delivery app with real-time tracking',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Aissatou Cisse',
        rating: 5,
        comment: 'Very skilled developer. Our app is performing excellently!',
        commentFr: 'Développeur très compétent. Notre application fonctionne excellemment!',
        date: '2026-03-25',
      },
    ],
  },
  {
    id: '6',
    name: 'Khadija Bah',
    title: 'Graphic Designer',
    location: 'Banjul, Gambia',
    avatar: 'https://i.pravatar.cc/150?img=44',
    rating: 4.9,
    reviewCount: 43,
    projectsCompleted: 49,
    hourlyRate: 27,
    skills: ['Photoshop', 'Illustrator', 'InDesign', 'Logo Design', 'Brand Identity', 'Print Design'],
    bio: 'Creative graphic designer specializing in brand identity and visual communication. I bring your vision to life.',
    bioFr: 'Designer graphique créative spécialisée dans l\'identité de marque et la communication visuelle. Je donne vie à votre vision.',
    languages: ['English', 'French', 'Mandinka'],
    portfolio: [
      {
        id: '1',
        title: 'Brand Identity Package',
        titleFr: 'Package d\'Identité de Marque',
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=500',
        description: 'Complete brand identity for new restaurant',
      },
    ],
    reviews: [
      {
        id: '1',
        client: 'Bakary Darboe',
        rating: 5,
        comment: 'Beautiful designs that perfectly captured our brand!',
        commentFr: 'Beaux designs qui ont parfaitement capturé notre marque!',
        date: '2026-04-10',
      },
    ],
  },
];

export const dummyRequests = [
  {
    clientName: 'Jean Pierre',
    clientEmail: 'jean.pierre@example.com',
    clientPhone: '+221 77 123 4567',
    category: 'Web Development',
    projectTitle: 'Restaurant Website with Online Ordering',
    projectDescription: 'Need a website for my restaurant with online ordering system',
    budget: '500-1000 USD',
    timeline: '3 weeks',
    status: 'pending',
  },
  {
    clientName: 'Sarah Johnson',
    clientEmail: 'sarah@example.com',
    clientPhone: '+220 99 876 5432',
    category: 'Design',
    projectTitle: 'Startup Brand Identity',
    projectDescription: 'Logo and brand identity for new startup',
    budget: '300-500 USD',
    timeline: '1 week',
    status: 'in-progress',
  },
  {
    clientName: 'Ousmane Dieng',
    clientEmail: 'ousmane@example.com',
    clientPhone: '+221 70 555 1234',
    category: 'Content Writing',
    projectTitle: 'Tourism Website Blog Articles',
    projectDescription: 'Blog articles for tourism website - need 10 articles',
    budget: '200-400 USD',
    timeline: '2 weeks',
    status: 'completed',
  },
];

export const categories = [
  { id: 'web-dev', name: 'Web Development', nameFr: 'Développement Web', icon: '💻' },
  { id: 'mobile-dev', name: 'Mobile Development', nameFr: 'Développement Mobile', icon: '📱' },
  { id: 'design', name: 'Design', nameFr: 'Design', icon: '🎨' },
  { id: 'marketing', name: 'Digital Marketing', nameFr: 'Marketing Digital', icon: '📈' },
  { id: 'writing', name: 'Content Writing', nameFr: 'Rédaction de Contenu', icon: '✍️' },
  { id: 'video', name: 'Video Editing', nameFr: 'Montage Vidéo', icon: '🎬' },
];
